name: Build and deploy WAR app to VM Web App

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify -P test -DskipTests=false

      - name: Build with Maven
        run: mvn clean package -P prod -DskipTests=true

      - name: Upload application
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "target/messagerie.war"
          target: "/tmp/source"

      - name: Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo ${{ secrets.ROOT_PASSWORD }} | sudo -S mv /tmp/source/target/messagerie.war /var/lib/tomcat9/webapps/messagerie.war -f
            echo ${{ secrets.ROOT_PASSWORD }} | sudo -S systemctl restart tomcat9

